# Generated by Django 6.0.3 on 2026-03-13 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv_builder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('overall_score', models.IntegerField(blank=True, null=True, verbose_name='Overall Score')),
                ('summary_feedback', models.TextField(blank=True, verbose_name='Summary Feedback')),
                ('experience_feedback', models.TextField(blank=True, verbose_name='Experience Feedback')),
                ('education_feedback', models.TextField(blank=True, verbose_name='Education Feedback')),
                ('skills_feedback', models.TextField(blank=True, verbose_name='Skills Feedback')),
                ('formatting_feedback', models.TextField(blank=True, verbose_name='Formatting Feedback')),
                ('suggestions', models.JSONField(blank=True, default=list, verbose_name='Suggestions')),
                ('raw_response', models.TextField(blank=True, verbose_name='Raw AI Response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cv_builder.cv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Review',
                'verbose_name_plural': 'AI Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
