# Generated by Django 6.0.3 on 2026-03-13 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='Search Query')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('radius_km', models.FloatField(default=10.0, verbose_name='Radius (km)')),
                ('source', models.CharField(choices=[('google_maps', 'Google Maps'), ('pages_jaunes', 'Pages Jaunes'), ('linkedin', 'LinkedIn')], default='google_maps', max_length=20, verbose_name='Source')),
                ('results_count', models.IntegerField(default=0, verbose_name='Results Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=300, verbose_name='Business Name')),
                ('business_type', models.CharField(blank=True, max_length=100, verbose_name='Business Type')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Contact Person')),
                ('contact_role', models.CharField(blank=True, max_length=100, verbose_name='Contact Role')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='Source')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Rating')),
                ('is_saved', models.BooleanField(default=False, verbose_name='Saved')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_contacts', to=settings.AUTH_USER_MODEL)),
                ('search_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='job_search.searchquery')),
            ],
            options={
                'verbose_name': 'Business Contact',
                'verbose_name_plural': 'Business Contacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
