# Generated by Django 6.0.3 on 2026-03-13 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='cvs/imports/', verbose_name='Original File')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file_type', models.CharField(max_length=10, verbose_name='File Type')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Extracted Text')),
                ('parsed_data', models.JSONField(blank=True, default=dict, verbose_name='Parsed Data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_cvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imported CV',
                'verbose_name_plural': 'Imported CVs',
                'ordering': ['-created_at'],
            },
        ),
    ]
