# Generated by Django 6.0.3 on 2026-03-13 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Template Name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('preview_image', models.CharField(default='template-preview', max_length=100, verbose_name='Preview CSS Class')),
                ('primary_color', models.CharField(default='#2c3e50', max_length=7, verbose_name='Primary Color')),
                ('secondary_color', models.CharField(default='#3498db', max_length=7, verbose_name='Secondary Color')),
                ('font_family', models.CharField(default='Arial, sans-serif', max_length=100, verbose_name='Font Family')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CV Template',
                'verbose_name_plural': 'CV Templates',
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My CV', max_length=200, verbose_name='CV Title')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('summary', models.TextField(blank=True, verbose_name='Professional Summary')),
                ('photo', models.ImageField(blank=True, upload_to='cv_photos/', verbose_name='Photo')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('pdf_file', models.FileField(blank=True, upload_to='cvs/pdf/', verbose_name='PDF File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_builder.cvtemplate')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CVEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='Institution')),
                ('degree', models.CharField(max_length=200, verbose_name='Degree')),
                ('field_of_study', models.CharField(blank=True, max_length=200, verbose_name='Field of Study')),
                ('start_date', models.CharField(max_length=20, verbose_name='Start Date')),
                ('end_date', models.CharField(blank=True, max_length=20, verbose_name='End Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='cv_builder.cv')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CVExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Company')),
                ('position', models.CharField(max_length=200, verbose_name='Position')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('start_date', models.CharField(max_length=20, verbose_name='Start Date')),
                ('end_date', models.CharField(blank=True, max_length=20, verbose_name='End Date')),
                ('current', models.BooleanField(default=False, verbose_name='Current')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='cv_builder.cv')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CVLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Language')),
                ('proficiency', models.CharField(blank=True, max_length=20, verbose_name='Proficiency')),
                ('order', models.PositiveIntegerField(default=0)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cv_builder.cv')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CVSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Skill')),
                ('level', models.IntegerField(default=3, verbose_name='Level')),
                ('order', models.PositiveIntegerField(default=0)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv_builder.cv')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
