# Generated by Django 5.2.12 on 2026-03-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='custom_primary_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Custom Primary Color'),
        ),
        migrations.AddField(
            model_name='cv',
            name='custom_secondary_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Custom Secondary Color'),
        ),
        migrations.AddField(
            model_name='cv',
            name='custom_sidebar_width',
            field=models.IntegerField(default=35, verbose_name='Sidebar Width (%)'),
        ),
    ]
